### ISSUE TITLE
Aggregation parameters: mismatch between actual & doc'd

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#115]
There are two discrepancies between the documented parameters of the `cf.aggregate` function and the actual parameters it accepts, namely:
* `cf.aggregates` takes the undocumented parameters, with defaults, `ignore=None` & `exclude=False`;
  https://github.com/NCAS-CMS/cf-python/blob/db0a9f82394f9c68f701bf3c09ea3185f02a39bc/cf/aggregate.py#L1293-L1294
* the [corresponding API reference describes](https://ncas-cms.github.io/cf-python/function/cf.aggregate.html?highlight=ignore) undefined parameters `exist_ignore` and `equal_ignore` (with no specific defaults indicated in the summary text):

    ```pycon
    >>> a = cf.example_field(0)
    >>> b = cf.aggregate(a, equal_ignore=False)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/sadie/cfdm/cfdm/decorators.py", line 186, in verbose_override_wrapper
        return method_with_verbose_kwarg(self, *args, **kwargs)
    TypeError: aggregate() got an unexpected keyword argument 'equal_ignore'
    >>> b = cf.aggregate(a, exist_ignore=False)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/sadie/cfdm/cfdm/decorators.py", line 186, in verbose_override_wrapper
        return method_with_verbose_kwarg(self, *args, **kwargs)
    TypeError: aggregate() got an unexpected keyword argument 'exist_ignore'
    ```

(I double-checked and found those are the only mismatches.)

It seems most likely given the equal number of parameters missing in each case that the pair of undocumented parameters were intended as the pair of documented but undefined parameters, but both having been given the wrong name in the API reference. I just want to check that this is indeed the case, and whether the mapping is (as there is not much in the logic to indicate potential matches & from the dev history it seems the mismatch was there [as far back as at least 2015](https://bitbucket.org/cfpython/cf-python/src/660265561a63e269a44c853b167f9cbff63e10e5/cf/aggregate.py?at=master)):

* `ignore` -> `equal_ignore`;
* `exclude` -> `exist_ignore`;

or vice versa. Arrows indicate the direction of change, as well, since to avoid an API change it seems preferable to re-document the mapping than to make an equivalent re-name of the parameters, do you agree @davidhassell ?

While we are considering it, I feel these names could be difficult to distinguish from each other in function without having to look-up the definitions, so perhaps we could rename them to try to make them more distinctive? Or do your recall naming these parameters was difficult such that these names might be the best possible?

**Comment by davidhassell** [comment]
Hi Sadie, 

Apologies for the confusion. It's a mess! I'm still looking at the code and trying to understand it myself ...

**Comment by davidhassell** [comment]
Does #123 make things clearer?

**Comment by sadielbartholomew** [comment]
> Apologies for the confusion. It's a mess! I'm still looking at the code and trying to understand it myself ...

That's okay. Given that no users have reported this after so long implies that these ignore options aren't used much if at all. But maybe with increased clarity about what they are, they might be...

#123 looks great from a skim read of the change set. Consolidating into one option is much preferred, in my opinion, if there is no difference in the motivation for the two that were documented but not implemented. I'll do a review of the branch for that PR to check more thoroughly. Thanks.

**Comment by sadielbartholomew** [comment]
I was about to comment that #123 closes this, but the one thing that remains is to document the `exclude` parameter (sorry I missed this in review for #123). Can you pop in a description to the docstring, @davidhassell?

**Comment by davidhassell** [comment]
Thanks, @sadielbartholomew. `exclude` is now documented: https://github.com/NCAS-CMS/cf-python/commit/afa1aab78e8523b26e1fe5a9e37309bb43be96b2

**Comment by sadielbartholomew** [comment]
Thanks @davidhassell, that's great.
