### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by statiksof** [NCAS-CMS/cf-python#119]
Any help for this issue?

https://github.com/NCAS-CMS/cf-training/issues/1

**Comment by sadielbartholomew** [comment]
Thanks for raising that error @statiksof. It looks like Andy is on the case as detailed over on the cf-training repo, so I will close this here as strictly it does not relate to cf-python but cf-plot.
