### ISSUE TITLE
Verify support for Python 3.9 (once it is more established)

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#132]
As per the description in NCAS-CMS/cfunits#15, though in this case I have not yet tried to add 3.9 jobs to the workflow to run the test suite (if setting up the environment for cfunits fails at the moment, it certainly will do the same for cf-python).

In short: **in late 2020 or early 2021** once 3.9 is more established and probably supported by at least some dependencies, we should check whether our dependencies allow us to support 3.9, and document (perhaps package) whether or not 3.9 is supported.

**Comment by davidhassell** [comment]
Reviewing mid December 2020 sounds good to me, too. Thanks.
