### ISSUE TITLE
Separate Action workflow to test on new source distribution

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#136]
In the lead up to release 3.7.0 we observed several sub-tests throw errors when run against a freshly-created source distribution (i.e. via `python setup.py sdist` then `./test_release <vn>`), even though they passed when the test suite ran against the git repo codebase (i.e. via `python run_tests.py` in the `cf/test/` dir).

In order to spot any such errors as they arise instead of only at release time, we can have an Actions workflow job which will run the source distribution test (just for one platform and Python version I think, no need to run it for each matrix combo).

This work will also help towards #134.

**Comment by davidhassell** [comment]
All sounds good to me.
