### ISSUE TITLE
More careful handling of Field-based collapse weights

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#141]
(As originally spotted by a user.)

This may not be a considered a bug as such, but could be handled better. Note the error from the following collapse:

```pycon
>>> import cf
>>> f = cf.example_field(1)
>>> f[0].collapse(axes='area', method='variance', weights=f[0].cell_area)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sadie/cf-python/cf/decorators.py", line 60, in precede_with_kwarg_deprecation_check
    operation_method_result = operation_method(self, *args, **kwargs)
  File "/home/sadie/cfdm/cfdm/decorators.py", line 186, in verbose_override_wrapper
    return method_with_verbose_kwarg(self, *args, **kwargs)
  File "/home/sadie/cf-python/cf/field.py", line 10481, in collapse
    great_circle=great_circle)
  File "/home/sadie/cf-python/cf/field.py", line 6699, in weights
    for w in tuple(weights):
TypeError: 'method' object is not iterable
```

This also occurs for the same call with a method of 'mean', and others, but not for calls with other collapse methods such as:

```pycon
>>> f[0].collapse(axes='area', method='median', weights=f[0].cell_area)
<CF Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(1), grid_longitude(1)) K>
```

Note also that in all cases (that I sampled), specifying `cell_area()` instead of `cell_area` alone for the weights won't lead to an error:

```pycon
>>> f[0].collapse(axes='area', method='variance', weights=f[0].cell_area())
<CF Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(1), grid_longitude(1)) K2>
>>> f[0].collapse(axes='area', method='median', weights=f[0].cell_area())
<CF Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(1), grid_longitude(1)) K>
```

which I think is the root of the problem; weights which are the former, i.e. bound methods on `Field`s, rather than the latter, field constructs, are not accounted for by the code such that it runs into some logic that is not appropriate for it and errors.

**Comment by davidhassell** [comment]
Hi @sadielbartholomew - yes, I agree we should put in a check for the given weights object being iterable at https://github.com/NCAS-CMS/cf-python/blob/master/cf/field.py#L6699, which might not be too bad, as by this stage we've already ruled out it being a string, a dict, a Field object, and a Data object. Perhaps replacing line https://github.com/NCAS-CMS/cf-python/blob/master/cf/field.py#L6699 with 

```
                try:
                    weights = iter(weights)
                except TypeError:
                    raise TypeError("Invalid type of 'weights' parameter: {}".format(weights))

                for w in weights:
```

There is still scope for problems if, say, a numpy array of weights is provided, but this was a problem before, too, so we're not making anything worse!
 
The reason it always works for the finding the median is that it is a non-weighted operation, so the weights are simply ignored, whatever they are:

```
>>> f.collapse(axes='area', method='median', weights='qwerty')
<CF Field: air_temperature(atmosphere_hybrid_height_coordinate(1), grid_latitude(1), grid_longitude(1)) K>
```

We could also consider raising an exception if the `weights` parameters is not `None` for non-weighted operations (median, maximum, minimum, sample_size, etc.). However, the reason that setting the weights for non-weighted operations has been allowed is that the default value of `weights` is a setting in itself, and there is more than one way to specify equal weights, with `weights=None` is just one of them (https://ncas-cms.github.io/cf-python/method/cf.Field.weights.html). So I not so keen on changing this.

**Comment by sadielbartholomew** [comment]
Thanks for the explanations and thoughts, @davidhassell.

> The reason it always works for the finding the median is that it is a non-weighted operation, so the weights are simply ignored, whatever they are

Ah, I see, it sounds so obvious when you mention it!

If weights are ignored, might it be good to inform the user about this, not as a warning but maybe an 'INFO' level logging call? A user could think there is weighting being done when it is not, otherwise.

> I agree we should put in a check for the given weights object being iterable ...

Actually I was thinking about catching the culprits at hand (the bound methods) at an earlier point, as a separate case, unless you can think of a reason that would not be wise. I've just added the following and from some interactive exploration it seems to work well:

```diff
diff --git a/cf/field.py b/cf/field.py
index a8eef0f2c..75fe36f9b 100644
--- a/cf/field.py
+++ b/cf/field.py
@@ -6669,6 +6669,9 @@ class Field(mixin.PropertiesData,
                 else:
                     comp[tuple(key)] = value.copy()
 
+        elif hasattr(weights, '__self__'):  # is a bound method
+            weights = weights()  # call bound method to get intended object
+
         elif isinstance(weights, self.__class__):
             # --------------------------------------------------------
             # Field
```
and I am waiting on the test suite to finish to check it does not cause unintended problems.

I forgot to mention my main thought in the opening comment, which is that while a bound method such as `cell_area` is not strictly a valid option, as per the documentation of valid weight specifications into those three types, it seems plausible that a user might specify that instead of a call to it. The user who reported something that led to me raising this had indeed done that.

So I'll push the commit with that `diff` assuming the tests all pass, and you don't respond with an objection. Catching it on the iteration seems like catching the issue further upstream than necessary to me.

> So I not so keen on changing this.

Sounds wise, I'll not touch anything else in the relevant code!

**Comment by davidhassell** [comment]
Hi @sadielbartholomew  - I appreciate the intention here, but  I think that running `weights = weights()` is too dangerous for me! In the example that got all this going (`cell_area`) there are method parameters which would all get their default values, which could lead to a "silently plausible" incorrect result.

Also, if a function (rather than bound method) were passed in then there would be no  `__self__` attribute, but it's really the same category of problem.

So, all in all, I think I still prefer my [previous suggestion](https://github.com/NCAS-CMS/cf-python/issues/141#issuecomment-721596872) of just trapping all non-iterables and giving a better error message. What do you think?

(In reflection, I think that there is no bug here - rather we are enhancing)

**Comment by sadielbartholomew** [comment]
> but I think that running weights = weights() is too dangerous for me!

Fair enough, it possibly could lead to something nasty if someone tries to pass in something more exotic. Okay, I'll implement your suggestion.

Yes, I don't think it is a bug, just an edge case that could fairly easily be called and hence one we should account for else provide a more useful error message.

**Comment by davidhassell** [comment]
Ok - sounds good to me. Thanks for covering all the bases on the this.
