### ISSUE TITLE
Improve performance of cf.aggregate

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#144]
An issue to track progress of the work to make `cfa` more performant, which I will begin soon.

As there will be continuous profiling involved, I am thinking it might be useful for me to create a wiki against the repo to document any significant measurements, analysis and attempted approaches to achieve speedup.

**Comment by sadielbartholomew** [comment]
Ah, that's a more pertinent description (title), thanks @davidhassell 👍

**Comment by davidhassell** [comment]
Closed by #647
