### ISSUE TITLE
Extend indexed assignment and binary operations to bounds, if present. 

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cf-python#146]
Currently, indexed assigment ignores bounds:
```python
>>> f = cf.example_field(0)
>>> a = f.dimension_coordinate('X')
>>> a.array
array([ 22.5,  67.5, 112.5, 157.5, 202.5, 247.5, 292.5, 337.5])
>>> a.bounds.array 
array([[  0.,  45.],
       [ 45.,  90.],
       [ 90., 135.],
       [135., 180.],
       [180., 225.],
       [225., 270.],
       [270., 315.],
       [315., 360.]])
>>> a[1:3] = 999
>>> a.array
array([ 22.5, 999. , 999. , 157.5, 202.5, 247.5, 292.5, 337.5])
>>> a.bounds.array
array([[  0.,  45.],
       [ 45.,  90.],
       [ 90., 135.],
       [135., 180.],
       [180., 225.],
       [225., 270.],
       [270., 315.],
       [315., 360.]])
```
which I think is fine when RHS does not have bounds (like `999`), but I don't think it makes sense when the RHS itself has bounds. Currently this happens:
```python
>>> f = cf.example_field(0)
>>> a = f.dimension_coordinate('X')
>>> a[...] = -1 * a
>>> a.array
array([ -22.5,  -67.5, -112.5, -157.5, -202.5, -247.5, -292.5, -337.5])   # -ve
>>> a.bounds.array
array([[  0.,  45.],    # +ve
       [ 45.,  90.],
       [ 90., 135.],
       [135., 180.],
       [180., 225.],
       [225., 270.],
       [270., 315.],
       [315., 360.]])
```

I'm not sure why this is so.

I propose extending assigmant to the bounds when both the LHS and RHS have bounds. i.e.:
```python
# Proposed behaviour

>>> f = cf.example_field(0)
>>> a = f.dimension_coordinate('X')
>>> a[...] = -1 * a
>>> a.array
array([ -22.5,  -67.5, -112.5, -157.5, -202.5, -247.5, -292.5, -337.5])  # -ve
>>> a.bounds.array
array([[  -0.,  -45.],  # -ve
       [ -45.,  -90.],
       [ -90., -135.],
       [-135., -180.],
       [-180., -225.],
       [-225., -270.],
       [-270., -315.],
       [-315., -360.]])
```

(As an aside, I realise that unary operations also ignore bounds but binary ones don't (always) - that'll be another issue, though.)

**Comment by davidhassell** [comment]
Note that when the RHS does _not_ have bounds, the assignment would only be on the data, and not the bounds data.

**Comment by davidhassell** [comment]
This should also apply to binary operations (such as `__add__`). I.e. if the LHS and RHS both have bounds then the bounds are also combined.

**Comment by davidhassell** [comment]
If `x` has bounds and `y` does not, what is least surprising:

**1.** `x + y` has bounds, whose values are `a.data.insert_dimension(-1) * b.bounds.data`

**2.** `x + y` has no bounds

The current PR #148 and 3.7.0 currently do case **1**.

There are, however, circumstances when either of these is desired. For example, consider the equation `a + b * orog`, as used in https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#atmosphere-hybrid-height-coordinate. `orog` never has bounds, and if `a` _and_ `b` do,  then we want case **1**. However, if only one of `a` or `b` has bounds then we want case **2**!

What should the default action be? Regardless of what it is, one can always deal with it in any given case, but we should apply the "do the least surprising thing that has the least chance of silently producing incorrect results" principle.

I now think I have best thing is to apply case **2**. Better to have no bounds than risk having unintended ones. This is also notionally more consistent with the `__setitem__`  behaviour being proposed. How does that sound?

**Comment by davidhassell** [comment]
Sorry, I forgot to mention the case `x + 2`. `2` has no bounds, but we probably would want to add 2 to `x`'s bounds by default. Hmm.

**Comment by davidhassell** [comment]
Sorry - I am confusing myself!

This is sounding very complicated and prone to misunderstanding.

There is also the question that if bounds on `x` are not updated (for whatever reason), should they be deleted?

Help!

**Comment by davidhassell** [comment]
.... Perhaps this is something which could be controlled by a global environment variable, that would turn on/off case **1.** Something like:
```python
>>> old = cf.do_something_clever_with_bounds(True)
>>> c = a + b * orog
>>> cf.do_something_clever_with_bounds(old)
```

assuming we went with **2** as the default, this would be nicer because it would prevent having to write complicated expressions twice, with wrapping if statements and dimension inserting:

```python
# Yuck

>>> c = a + b * orog
>>> if a.has_bounds() and b.has_bounds():
        orog = orog.insert_dimension(-1)
        c_bounds = a.bounds + b.bounds * orog
        c.set_bounds(c_bounds)
```

**Comment by davidhassell** [comment]
Here's where I think we're at:

* Create a new function `cf.combine_bounds_with_coordinates` (good name?) that controls the behaviour of binary arthmetic operations.

* Define the behaviour when bounds are present as follows:

  | `cf.combine_bounds_with_coordinates()` | `x` has bounds     | `y` has bounds | `z = x + y` has bounds |  Notes | 
  | ----------- | ----------- | ----------- | ----------- | ----------- |
  | False (default) | Yes    | Yes       | **Yes** |  `z.bounds` is `x.bounds + y.bounds` | 
  | False (default) | Yes  | No        | _No_ |  | 
  | False (default) | No    | Yes       | _No_ |  | 
  | False (default) | No  | No        | _No_ | | 
  | True | Yes    | Yes       | **Yes** |   `z.bounds` is `x.bounds + y.bounds`  | 
  | True | Yes  | No        | **Yes**|   `z.bounds` is `x.bounds + y`  | 
  | True | No    | Yes       | **Yes** |   `z.bounds` is `x + y.bounds`  | 
  | True | No  | No        | _No_|  |

----

**Notes**

* Note what happens if `y` is `1` ...

  | `cf.combine_bounds_with_coordinates()` | `x` has bounds   | `z = x + 1` has bounds |  Notes | 
  | ----------- | ----------- | ----------- | ----------- |
  | False (default) | Yes          | _No_ |  _(a)_ | 
  | False (default) | No      | _No_ |  | 
  | True | Yes          | **Yes** |  _(b)_ `z.bounds` is `x.bounds + 1` | 
  | True | No      | _No_ |  |

  ... which is different to the behaviour at 3.7.0, for which  case _(a)_ gives the behaviour of case _(b)_.

* Consider ...

  | `cf.combine_bounds_with_coordinates()` | `x` has bounds   | `z = x * -1` has bounds |  Notes | 
  | ----------- | ----------- | ----------- | ----------- |
  | False (default) | Yes          | _No_ |  _(c)_ | 
  | False (default) | No      | _No_ |  | 
  | True | Yes          | **Yes** |  _(d)_ `z.bounds` is `x.bounds * -1` | 
  | True | No      | _No_ |  |

  ... this is looks similar to the unary operation `z = -x`, for which issue #147 has just made case _(c)_ behave like case _(d)_. I   think that is is OK for this particular unary operation to behave differently to its binary operation equivalent, because it ensures that `x - y` will always give the same result as `-y + x` in all cases.

* The unary operations are unaffected by `cf.combine_bounds_with_coordinates`, e.g.

  | `cf.combine_bounds_with_coordinates()` | `x` has bounds   | `z = -x` has bounds |  Notes |   
  | ----------- | ----------- | ----------- | ----------- |
  | False (default) | Yes          | **Yes** | `z.bounds` is `x.bounds * -1` | | 
  | False (default) | No      | _No_ |  | 
  | True | Yes          | **Yes** |  `z.bounds` is `x.bounds * -1` | 
  | True | No      | _No_ |  |

**Comment by sadielbartholomew** [comment]
@davidhassell there's a lot to think about here, but generally I think your proposal is the most sensible in context. The tables in your previous comment are really useful and I think it would be great to lift or adapt at least the first one to put in the documentation when to explain the behaviour (though that was possibly your intention already).

> Create a new function cf.combine_bounds_with_coordinates (good name?) that controls the behaviour of binary arthmetic operations.

The name is possibly a bit longer than ideal, though I appreciate both 'bounds' and 'coordinates' probably need to be in the name to make it descriptive enough and therefore that is about as short as possible. Possibly we could have a shorter alias to go with it?

**Comment by davidhassell** [comment]
Thanks, Sadie.

I have put the tables into the various docstrings in the updated PR #148 

I'm having second thoughts about having "coordinates" in the name, as when we combine things-with-bounds with things-which aren't-coordinates (like `b * orog` in my previous examples), the name is misleading. Any ideas? I like the idea of an alias if we can't get it short enough to be convenient.

**Comment by sadielbartholomew** [comment]
Thanks David that all sounds good.

One point to add, probably too late anyway but I'll put it here anyway: I was thinking about how this closely resembles truth tables on whether `x` and `y` have bounds, which made me wonder if it might be more intuitive (though a second opinion is definitely needed this could well be making it much less so instead) and allow for more flexibility, if the bounds combination behaviour was defined with binary logical operations, so 'AND' and 'OR', and possibly also 'XOR' if there could be some use case for that? So going by your tables, 'AND' would be the default, it would change to 'OR' when `cf.combine_bounds_with_coordinates` is set to `True`.

So I guess that could provide an alternative approach of having a non-Boolean setting `cf.bounds_combination_logic` where the possibilities, which could be an `enum`, would be 'AND', 'OR', 'XOR', and I guess 'FALSE' too if the user did not want `z` to have bounds in any case. Would that be too complicated or excessive anyhow? I guess it would assume the user has familiarity with basic Boolean logic (though being mostly scientists and similar that is probably okay to assume).

> I'm having second thoughts about having "coordinates" in the name, as when we combine things-with-bounds with things-which aren't-coordinates (like b * orog in my previous examples), the name is misleading. Any ideas?  I like the idea of an alias if we can't get it short enough to be convenient.

Unless you are so swayed by the above idea that you want to change your PR code, which I realise is unlikely, I can't see anything that would be wrong with just `cf.combine_bounds`? Then it would already be short enough to be convenient on its own.

**Comment by davidhassell** [comment]
I very much like this idea, as the boolean approach fits _my_ use case (#142), but probably doesn't fit everyone's. It also makes it much easier to understand and describe.

Very happy to change the PR - it's not much code anyway and any changes now are essentially just messing with the if statements. Shall we talk about it tomorrow?

**Comment by sadielbartholomew** [comment]
> Shall we talk about it tomorrow?

Sounds like a plan, @davidhassell. I'll hold the review in that case until we chat about what's best. Thanks.

**Comment by davidhassell** [comment]
Here are the truth tables for the extended functionality:

Flag | x has bounds | y has bounds | z = x + y has bounds | Notes
-- | -- | -- | -- | --
`'AND'`  | Yes | Yes | **Yes** | `z.bounds` is `x.bounds + y.bounds`
`'AND'`  | Yes | No | _No_ |  
`'AND'`  | No | Yes | _No_ |  
`'AND'`  | No | No | _No_ |

Flag | x has bounds | y has bounds | z = x + y has bounds | Notes
-- | -- | -- | -- | --
`'OR'` | Yes | Yes | **Yes** | `z.bounds` is `x.bounds + y.bounds`
`'OR'` | Yes | No | **Yes** | `z.bounds` is `x.bounds + y`
`'OR'` | No | Yes | **Yes** | `z.bounds` is `x + y.bounds`
`'OR'` | No | No | _No_ |

Flag | x has bounds | y has bounds | z = x + y has bounds | Notes
-- | -- | -- | -- | --
`'XOR'` | Yes | Yes | _No_ |
`'XOR'` | Yes | No | **Yes** | `z.bounds` is `x.bounds + y`
`'XOR'` | No | Yes | **Yes** | `z.bounds` is `x + y.bounds`
`'XOR'` | No | No | _No_ |

Flag | x has bounds | y has bounds | z = x + y has bounds | Notes
-- | -- | -- | -- | --
`False` | Yes | Yes | _No_ |
`False` | Yes | No | _No_ |
`False` | No | Yes | _No_ |
`False` | No | No | _No_ |

The use case I posted earlier would look like (experimenting with a new function name):

```python
>>> old = cf.bounds_treatment('OR' if a.has_bounds() and b.has_bounds() else 'AND')
>>> c = a + b * orog
>>> cf.bounds_treatment(old)
```

I like quite like this, as it makes if very clear what we expect this code to do, whatever the inputs.

**Comment by davidhassell** [comment]
Possible name:

`cf.bounds_treatment`

`cf.operand_bounds_treatment`

`cf.operation_bounds_treatment`

`cf.combintation`

`cf.operand_bounds_combitation`

`cf.operation_bounds_combination`

**Comment by davidhassell** [comment]
Wondering if `False` should be `'NONE'`, instead, so that the returned type of the function is always of the same type (i.e. `str`).

**Comment by davidhassell** [comment]
@sadielbartholomew  - should the flag also apply to assignment by index. E.g.


Flag | x has bounds | y has bounds | For x[...] = y, x has bounds | Notes
-- | -- | -- | -- | --
`'AND'` | Yes | Yes | **Yes** | `x.bounds` is `y.bounds`
`'AND'` | Yes | No | _No_ |  
`'AND'` | No | Yes | _No_ |  
`'AND'` | No | No | _No_ |  


Flag | x has bounds | y has bounds | For x[...] = y, x has bounds | Notes
-- | -- | -- | -- | --
`'OR'` | Yes | Yes | **Yes** | `x.bounds` is `y.bounds`
`'OR'` | Yes | No | **Yes** | `x.bounds` is unchanged
`'OR'` | No | Yes | **Yes** | `x.bounds` is `y.bounds`
`'OR'` | No | No | _No_ |  

???

This approach would at least be consistent.

**Comment by davidhassell** [comment]
If the function applies to assignment as well, I'm veering towards `cf.operand_bounds_treatment`

**Comment by sadielbartholomew** [comment]
Trying to follow your train of thought, @davidhassell, to work out what has been ironed out and what remains to be decided.

> Wondering if False should be 'NONE', instead, so that the returned type of the function is always of the same type (i.e. str).

Are you suggesting just a change to the proposed name, or to the discussed behaviour? In the latter case I am not sure quite what is intended, so please elaborate if that's okay, but regarding the name I agree that 'NONE' would be better than 'False'.

Regarding possible names for the global control function itself, I had some other options to add to the list:

* `combine_bounds_with` (`combine_bounds_according_to` ideally, but that's a bit too long), as in ``combine_bounds_with(<this rule>)` or `...(that rule`);
* `bounds_combination_rule` or `_mode`.

Though I still don't have a strong preference for any of the options set out so far, nor a reason to think any of them aren't good. I was thinking though that with certain names, such as `combine_bounds_with`, the 'NONE' option might be better named 'NEVER'. So the most appropriate name for that option might be best decided when we set the name of the function.

> There is also the question that if bounds on x are not updated (for whatever reason), should they be deleted?

Do you think we have resolved this question yet, as I am not quite sure?

**Comment by davidhassell** [comment]
Thanks for adding clarity.

> Are you suggesting just a change to the proposed name, or to the discussed behaviour? In the latter case I am not sure quite what is intended, so please elaborate if that's okay, but regarding the name I agree that 'NONE' would be better than 'False'.

The former. Same behaviour, just a different name.

> There is also the question that if bounds on x are not updated (for whatever reason), should they be deleted?

I think that this has been answered by the [subsequently defined truth tables](https://github.com/NCAS-CMS/cf-python/issues/146#issuecomment-725397731). These tell us that bounds on x are, in any case, either updated or deleted.

New proposed names:

`cf.combine_bounds_with`
`cf.combine_bounds_according_to`
`cf.bounds_combination_rule`
`cf.bounds_combination_mode`

I like  `cf.bounds_combination_mode`.

I'm not so keen on `'NEVER'` as it might imply (to me, at least) that bounds could be not combined yet retained in the result, which is not possible.

**Comment by davidhassell** [comment]
@sadielbartholomew 

> Edit - this is a bad idea, I reckon, I'm pretty sure that we don't want to create bounds by assignment when those didn't exist before.

For the record, I'm not _very_ sure we don't want to do this, as we can't set bounds on only a part of the construct.

**Comment by sadielbartholomew** [comment]
> I think that this has been answered by the subsequently defined truth tables. These tell us that bounds on x are, in any case, either updated or deleted.

Ah yes, of course, so when the result has no bounds that is because they were deleted (naturally). Thanks for verifying.

> I'm not so keen on 'NEVER' as it might imply (to me, at least) that bounds could be not combined yet retained in the result, which is not possible.

Good point, let's not use 'NEVER' in that case.

> I'm currently thinking that 'NONE' is the only sensible option for these, but I'd like to think about it some more.

Fair enough. Is the PR in a draft mode essentially due to this, or otherwise? We could always put in 'NONE' for all cases with simple geometries for now and then do a follow-up PR.

> SHould these case assume 'NONE' whatever the global setting? Or if the global setting is not 'NONE' should an exception be raised ... ?

It's definitely a good idea to at least warn users if they are asking to do something that doesn't make sense, but I'm not sure it should be a blocking exception. A strongly-worded warning would be my preference, I think. Although I guess it depends quite how non-sensical it is to combine bounds in a given case.

**Comment by davidhassell** [comment]
> Fair enough. Is the PR in a draft mode essentially due to this, or otherwise? We could always put in 'NONE' for all cases with simple geometries for now and then do a follow-up PR.
>
> It's definitely a good idea to at least warn users if they are asking to do something that doesn't make sense, but I'm not sure it should be a blocking exception. A strongly-worded warning would be my preference, I think.

Good question. Geometries are also special because they may reasonably exist without representative coordinate values. If wanted to shift some geometry coordinates by 5 degrees of longitude with `x + 5`, then we would want that operation to apply to the coordinates (if present) and the bounds; the interior ring values (if present) would remain unchanged.

If we did `x + y` where `y` may/may not have bounds/interior_ring then perhaps it's not as bad as I feared: https://github.com/davidhassell/cf-python/commit/3766330eb255032dafd95b76f0fd60be6ddf9e0f

**Comment by davidhassell** [comment]
Hi Sadie. PR #148 looks in good shape - thanks for the review. The only thing outstanding is the name of the function ... what are you currently in favour of?

**Comment by sadielbartholomew** [comment]
> The only thing outstanding is the name of the function ... what are you currently in favour of?

@davidhassell I think all of the options we have converged on are appropriate and concise enough to not warrant aliasing. I don't have any preference or indeed reasons to not think any are good, so if you have any preference whatsoever then please go ahead and select it. Otherwise let's choose one by some quick means so as not to be indecisive (we could perhaps do a quick poll on the cf-python Slack channel).

**Comment by davidhassell** [comment]
OK, thanks. I'm happy to choose here and now. Let's go with ...  `cf.bounds_combination_mode`.

I'll update the PR.
