### ISSUE TITLE
Rename master branch to 'main'

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#190]
GitHub has made the switch from calling the default branch of a repository 'main' rather than 'master' (given the slavery connotations as far as I have read) so to keep up with the times we should eventually rename our `master` branches on cf-python, cfdm and cfunits accordingly.

I think a sensible time to make the change would be right after we merge in the `dask` branch ready for a 4.0.0 release of cf-python. We can update our development workflows (including GitHub Actions workflows) and local branches and aliases etc., as well as the developer documentation, then. I don't think it will take very long to sort, but I think best wait until the Dask work is in to make the name change across our repos.

**Comment by davidhassell** [comment]
I heartily agree. Your proposed timeline sounds good. Thanks

**Comment by sadielbartholomew** [comment]
Now our Dask-migration release is out (v3.14.0 rather than v4.0.0 as per my original comment), I am going to make this conversion (this evening). I'll comment here and close this once I am done.
