### ISSUE TITLE
Add a `.gitignore` to e.g. not track test run changes

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#21]
There does not appear to be a ``.gitignore`` file anywhere in the repository, such that running the test suite produces a sizable set of changed files that ``git`` picks up on, & in particular one (``test_file.nc``) which it is under tracking & hence is listed as a ``diff`` made, which e.g. must be reset or committed to allow a change of branch.

This means it is hard to keep on top of the files that have been purposefully changed from development & to switch branches & housekeep. Ideally at least one ``.gitignore`` file could be added to exclude relevant files from version control to prevent those issues, & I have made a suggestion below based on files I observed to be modified during development.

I thought it best to register this as an Issue to confirm this would be desired, & check for a recommended approach to test run changes on files (see below).

For example after some development yesterday, then returning to a clean branch & not making any explicit code changes but running the test suite via ``python run_tests.py``, I saw:

```console
$ git diff
diff --git a/cf/test/test_file.nc b/cf/test/test_file.nc
index ad756f4..e812312 100644
Binary files a/cf/test/test_file.nc and b/cf/test/test_file.nc differ
$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   cf/test/test_file.nc

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	cf/__init__.pyc
	cf/__pycache__/
	cf/abstract/#coordinate.py#
	cf/abstract/.#coordinate.py
	cf/abstract/__pycache__/
	cf/data/__pycache__/
	cf/data/abstract/__pycache__/
	cf/mixin/__pycache__/
	cf/read_write/__pycache__/
	cf/read_write/netcdf/__pycache__/
	cf/read_write/um/__pycache__/
	cf/test/DSG_timeSeriesProfile_indexed_contiguous.nc
	cf/test/DSG_timeSeries_contiguous.nc
	cf/test/DSG_timeSeries_indexed.nc
	cf/test/__pycache__/
	cf/test/combined.nc
	cf/test/delme.nc
	cf/test/delme.nca
	cf/test/dir/
	cf/test/external.nc
	cf/test/external_missing.nc
	cf/test/gathered.nc
	cf/test/new_STASH_to_CF.txt
	cf/test/parent.nc
	cf/umread_lib/__pycache__/
	cf_python.egg-info/
	docs/source/class.rst.bak
	docs/source/field_analysis.rst.bak
	docs/source/tutorial.rst.bak
	docs/source/visualisation.rst.bak

no changes added to commit (use "git add" and/or "git commit -a")
```

Note the final four entries persisted after I made some docs changes in different branches previously, & the few listed files including '#' in their names are backups due to my use & user configuration of emacs for text editing (so not strictly related, but left in for illustration).

#### Suggested configuration

Something like the below added into the root project directory [would cover all of the above](https://git-scm.com/docs/gitignore#_pattern_format), except the emacs backups ([text editor backups etc. can be specified](https://github.com/github/gitignore/tree/master/Global) to exclude but is probably too costly in configuration volume requirements to capture for everyone as people use different editors/IDEs). That could then be extended to be useful in other contexts as they arise.

#### .gitignore:
```gitignore
# Exclude from version control...

# ... any '__pycache__' directory anywhere under the root directory
**/__pycache__/

# ... all .pyc & .pyo files
*.py[co]

# ... test files that change if & when the test suite is run
cf/test/*.nc
cf/test/*.nca
cf/test/*.txt
cf/test/dir/

# ... packaging-related files changing with environment adjustments
*.egg-info/

# ... backup files for the documentation etc.
docs/source/*.rst.bak
```

However, the files under ``cf/test/`` need consideration, since the above will exclude all files with those extensions under that directory, but there are plenty more files of that nature which don't seem to change from a test run. What is required is a means to differentiate between such files known to change after, or be generated during, a test run & those not, such that a more specific pattern can be used to exclude only the former. For example, renaming the former cases ``delete_<name>.<extension e.g. .nc>``.

Saying that, it might be best to housekeep (delete, revert to the original state, etc., at the end of a test run) the test files to prevent the issue in the first place, instead of using the ``.gitgnore``.

Thoughts would be appreciated.

**Comment by davidhassell** [comment]
Hi Sadie,

This would useful. 

```

**Comment by davidhassell** [comment]
Hi Sadie,

This would be a welcome addition to the repo. I think that differentiating between the two types of file  in `cf/test` is a good idea. Perhaps a sub-directory would be better for those which are to be ignored: `cf/test/generated/`, as I do use these files independently for command line testing.

In the longer term, it would be nice to review the tests so that *all* of the test files are generated, on-the-fly by, by `create_test_files.py`

**Comment by sadielbartholomew** [comment]
Thanks for your useful thoughts & advice, David. I will put in a PR to cover this in the next few days or so, taking them on board.

I'll include a movement of files to ignore for version control to a separate directory, as suggested, which sounds like a good solution. And I've noted down your thoughts for the longer term in my notebook.

**Comment by sadielbartholomew** [comment]
Resolved by commit https://github.com/NCAS-CMS/cf-python/commit/7f667236f4e1116d4caf3fdcf176d39c4b7cd4d4, so this can now be closed.
