### ISSUE TITLE
Error parsing file: AttributeError: 'numpy.float64' object has no attribute 'strip'

### ISSUE THREAD

**Issue by AJamesPhillips** [NCAS-CMS/cf-python#23]
With the following 1.2 Gb file (sorry I haven't reduced it in size yet but happy to try to do that to narrow down the problem) "Download the global GEBCO_2019 SID Grid" from https://www.gebco.net/data_and_products/gridded_bathymetry_data/

The following code errors:

```
import cf

f = cf.read("GEBCO_2019_SID.nc")
print(f)
```

> $ python process.py 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfunits/units.py", line 678, in __init__
>     units = units.strip()
> AttributeError: 'numpy.float64' object has no attribute 'strip'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "process.py", line 3, in <module>
>     f = cf.read("GEBCO_2019_SID.nc")
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cf/read_write/read.py", line 514, in read
>     chunk=chunk)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cf/read_write/read.py", line 710, in _read_a_file
>     extra_read_vars=extra_read_vars)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfread.py", line 854, in read
>     all_fields[ncvar] = self._create_field(ncvar)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfread.py", line 1985, in _create_field
>     self.implementation.set_properties(f, field_properties, copy=True)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfdm/read_write/cfdmimplementation.py", line 1771, in set_properties
>     construct.set_properties(properties, copy=copy)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cf/mixin/properties.py", line 979, in set_properties
>     setattr(self, prop, value)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cf/mixin/propertiesdata.py", line 1610, in units
>     self.Units = Units(value, getattr(self, 'calendar', None))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cf/units.py", line 16, in __new__
>     return cfUnits(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfunits/units.py", line 680, in __init__
>     raise ValueError("Can't set unsupported unit: {!r}".format(units))
> ValueError: Can't set unsupported unit: 1.0

**Comment by davidhassell** [comment]
Hi, could you post the output of `ncdump -h GEBCO_2019_SID.nc`. I seems that one of the netCDF variables has a `units` attribute whose value is a float which is not allowed (they must be strings). 

However, the `Units` object has been designed to store incorrect units and not raise an exception, setting its `isvalid` attribute to False instead:
```
In [13]: v = cf.Units('m')                                                      

In [14]: v.isvalid                                                              
Out[14]: True

In [15]: u = cf.Units('since 2019-01-01')                                       

In [16]: u.isvalid                                                              
Out[16]: False
```

So I think that the checking on what are/aren't valid units is lacking, which will require a fix in the `cfunits` library.

**Comment by davidhassell** [comment]
Fixed in `cfunits v3.2.3`. Upgrading `cfunits` (e.g with `pip install cfunits --upgrade`) will feed the fix into cf-python, and should allow the read of your file to proceed. Note that even though the read will not fail, something downstream might if you try to do something with the bad units (such as convert the data to different but equivalent units).

I'll close this when you confirm that your file can now be read.
```
In [1]: import cf     

In [2]: u = cf.Units(1.0)                    

In [3]: u           
Out[3]: <Units: 1.0>

In [4]: u.isvalid                          
Out[4]: False

In [5]: u.reason_notvalid  
Out[5]: "Bad units type: <class 'float'>"

In [6]: u.units      
Out[6]: 1.0
```
The minimum version of the `cfunits` dependency will be moved to 3.2.3 for cf-python v3.0.7

**Comment by davidhassell** [comment]
@AJamesPhillips did you get a chance to try reading your file with the newer `cfunits` version? Thanks.

**Comment by AJamesPhillips** [comment]
Sorry @davidhassell not yet.  It is on my todo list just completely snowed at the moment.  Please feel free to close this and I'll report back and optionally reopen this if there's a problem.

**Comment by davidhassell** [comment]
Thanks, I'll do that.

Note that the `override_units` method is the way to fix bad units, on a field or metadata construct:
```
>>> f.Units
<Units: 1.0>
>>> f.Units.isvalid
False
>>> f.Units.reason_notvalid
"Bad units type: <class 'float'>"
>>> f.override_units('1', inplace=True)
>>> f.Units  
<Units: 1>
>>> f.Units.isvalid
True
```
