### ISSUE TITLE
cf.Field.coordinate_reference API changed at 3.10.0

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cf-python#240]
The `cf.Field.coordinate_reference` API changed at 3.10.0. E.g. `field.coordinate_reference('rotated_latitude_longitude')` used to work, but now we need to use `field.coordinate_reference('grid_mapping_name:rotated_latitude_longitude')` to retrieve the construct.

At 3.9.0, both options worked, and should still work now.

**Comment by davidhassell** [comment]
OK, having put together a PR for this and wondered why a bunch of the unit tests started failing, I realise that perhaps we do want to keep the 3.10.0 behaviour after all.

This is related to the fact that a "bare" identity (one without `:` or `%` in it) is not discernable between a construct identifier (such as as `"coordinaterefernce1"`) and a meaningful name (such as `"rotated_latitude_longitude"`). This was the case pre 3.10.0 also. There is a very (very) remote chance that this confusion could cause an  error (possibly untrapped) in someone's code, so I think I'd prefer to take this opportunity to retain the 3.10.0 behaviour, i.e.

```python
>>> field.coordinate_reference('rotated_latitude_longitude')                     # does NOT work at v3.10.0 and beyond
>>> field.coordinate_reference('grid_mapping_name:rotated_latitude_longitude')   # works at all versions
```

@ThibHlln, is this satisfactory?

**Comment by ThibHlln** [comment]
Hi David,

Yes, this is absolutely fine. I have stopped using the "bare" identity already.
I understand the issue, and I think being more explicit is not a bad thing.

Thank you for taking the time to look into this.

**Comment by davidhassell** [comment]
Thanks, @ThibHlln, I'll close this one, now.
