### ISSUE TITLE
This library is amazing

### ISSUE THREAD

**Issue by AJamesPhillips** [NCAS-CMS/cf-python#25]
This library is amazing and even more so that you only started open sourcing it mid September.  Could I make a suggestion / request.

1) [The tutorial](https://ncas-cms.github.io/cf-python/tutorial.html) is really useful.  But it's a little hidden.  Perhaps you could also put "Getting started" somewhere in the intro paragraph it make it easier for people to find it from search engines.  [PR for also explicitly mentioning it in the README.md](https://github.com/NCAS-CMS/cf-python/pull/24) if you're interested.

2) Help / advice / mailing list / Stackoverflow
Obviously it's a new open source library but do you have a recommendation of where to go for help / advice?  For example I have a script that's iterating over 3 billion elements and it's taking a while (as expected) but perhaps it could be optimised in some way.  Would be good to put in a reference of the best place to ask for help.  (script below included as an example, not expecting help).  Actually maybe a second tutorial on advanced use including a section on optimisation / performance you can expect / gotchas / good v bad practices?  I've read the [performance](https://ncas-cms.github.io/cf-python/performance.html) page.  I think that exploring `cf.CHUNKSIZE` might be a good place to start with the below script but not sure.

```
import cf
import json

filename = "GEBCO_2019/GEBCO_2019.nc"
f1 = cf.read(filename, verbose=False)
d1 = f1[0].data

print(d1.shape)
lat_max = d1.shape[0]
lon_max = d1.shape[0]

SCALE = 50
x_chunks = int(lat_max / SCALE)
y_chunks = int(lon_max / SCALE)

for x in range(x_chunks):
  data = []
  x_prog = round((x * 100)/ x_chunks)
  print("progress: {}%".format(x_prog))
  data.append([])
  for y in range(y_chunks):
    print("progress: {}% . {}%".format(x_prog, round((y * 100)/ y_chunks)))
    chunk = d1[x * SCALE:(x + 1) * SCALE, y * SCALE:(y + 1) * SCALE]
    data[x].append(float(chunk.mean()))

  with open("scaled-elevation-{}-{}.json".format(x, SCALE), "w") as f:
    json.dump(data, f)
```

**Comment by davidhassell** [comment]
Hi - you are very kind, but it's actually been open source since 2011, but hosted on different sites (googlecode (https://code.google.com/archive/p/cf-python) and, from 2013 to September 2019 on bitbucket (https://bitbucket.org/cfpython/cf-python)

The chunks size can make a big difference when calculating statisics (`chunk.mean()` in you case). You can see how many partitions are in teh data by looking at `chunk._pmsize`. One trick, free memory permitting, is to consolidate all of the partitions into one large one prior to the calculation  - although this happens automatically if the data size is less than 1% of total memory on the machine:
```

**Comment by davidhassell** [comment]
As for where to get advice, I think that this issue tracker is currently the best place to get the attention of the developers.

**Comment by AJamesPhillips** [comment]
Great thank you David.  Increasing size of data operated on at once has definitely increased the speed.  And I assume therefore that IO is the bottleneck and that:

> consolidate all of the partitions into one large one prior to the calculation

brings all the data into memory from disk in an efficiency "single" step.  If so is there a way to load in larger areas of data before operating on smaller parts?  Perhaps something like this where an outer loop fetches a complete "row" of data before subsets are worked on:

```
outer-for-loops:
  LARGER = 10 * SCALE
  larger_chunk = d1[x * LARGER:(x + 1) * LARGER, y * LARGER:(y + 1) * LARGER]
  larger_chunk.force_load_data_from_disk # <= some function like this available?
  inner-for-loops:
    chunk = larger_chunk[x * SCALE:(x + 1) * SCALE, y * SCALE:(y + 1) * SCALE]
    # original code can use loaded data in memory for faster access?
    chunk.mean()
```

Apologies if this is an obvious question.  I [found varray here](https://ncas-cms.github.io/cf-python/genindex.html) but its description wouldn't have let me understand what you've kindly taught me here.  Also had a skim of the helpful [Resource Management](https://ncas-cms.github.io/cf-python/function.html#resource-management) but don't think there was anything relevant in there.

**Comment by davidhassell** [comment]
Have a look at https://ncas-cms.github.io/cf-python/method/cf.Data.to_memory.html

```
larger_chunk.to_memory(regardless=True)
```

The resource management docs haven't been changed for quite a long time - time for an overhaul, I think ....

**Comment by AJamesPhillips** [comment]
With `.to_memory(regardless=True)` processing time has dropped by 97% or 33x for one scenario and about 100x for another.  This also reduced total memory read from disk (according to Activity Monitor) by 25x from 1.6 TB to 65 GB (the file is only 12 GB on disk).  Means the data processing job on the 12 GB file that would have taken > 2 days this morning now takes < 30 minutes by using 4 `.to_memory` calls.

Thanks again for your amazing responsive help!  I'll close this issue now.
