### ISSUE TITLE
Restrict size 1 dimension to source field in regridding

### ISSUE THREAD

**Issue by ThibHlln** [NCAS-CMS/cf-python#250]
Hi David, Hi Sadie,

In the regridding functionality, there currently is a restriction on the size of the dimensions of the grid: any dimension needs to be greater than one. 

But after some testing, I found out that it is only problematic to have a size 1 dimension on the source grid, but not on the destination grid. Indeed, ESMF only raises an error when the source grid has a size 1 dimension (see https://github.com/esmf-org/esmf/blob/b4c535d3b3925f43ccad78191f40d6c51f6f2e7e/src/Infrastructure/Field/src/ESMF_FieldRegrid.F90#L2840-L2847). I am not sure what is the underlying reason for this restriction in ESMF, and it is surprising that it complains only for the source grid.

Nevertheless, as a user, I see some situations where I could benefit from the ability to regrid to a destination resolution composed of a single grid cell (e.g. pre-process some gridded data to get a lumped value for a given region). Since it seems to be working for all regridding methods, I thought it may be good to lift the restriction on the destination grid in `cf-python`.

What do you think? 
Also, do you have any idea why ESMF would restrict the size 1 dimension on the source grid only?

**Comment by davidhassell** [comment]
> Although, you need to remove the squeezing here: https://github.com/NCAS-CMS/cf-pytho/blob/6c4823d83ca0a3b6ca4d6da3a0d09e4c43b38ee1/cf/field.py#L15848 for it to work.

This needs a bit more treatment for the case when non-regridding axes have size 1. In this case we want to squeeze these non-regridding axes, but leave size-1 regridding axes alone. See https://github.com/NCAS-CMS/cf-python/commit/7dfb455d3f973d721560ddaee962007cdb1a1d4c for details.

**Comment by davidhassell** [comment]
... and the test:

```python
for m in ['conservative', 'conservative_2nd', 
          'nearest_stod', 'nearest_dtos']:
    fld3 = fld2.regrids(fld1, method=m)
    print(fld3.array)
```
works with https://github.com/NCAS-CMS/cf-python/commit/7dfb455d3f973d721560ddaee962007cdb1a1d4c, too.
