### ISSUE TITLE
Allow `n=6` example field to be written to classic netCDF-3

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#268]
See https://github.com/NCAS-CMS/cfdm/issues/140#issuecomment-932289534, and the `cfdm` issue holding that comment which applies here also, where I will re-state the permalink because it will render in-line here:

https://github.com/NCAS-CMS/cf-python/blob/124ed7d78f4eb3ba988a40f784ebef20eb578312/cf/test/test_read_write.py#L347-L351

**Comment by davidhassell** [comment]
Fixed by cfdm v1.9.0.1: https://github.com/NCAS-CMS/cfdm/pull/162
