### ISSUE TITLE
Missing closing parenthesis in Query object representations

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#279]
(Quick one, with a very easy fix I will push as a commit but I am raising as an issue in case it is worthy of a changelog note:) the `__str__` and `__repr__` representations for a `Query` are missing a closing parenthesis in the current `master`:

```pycon
>>> import cf
>>> cf.__version__
'3.11.0'
>>> q = cf.Query('le', 6)
>>> q
<CF Query: (le 6>
>>> print(q)
(le 6
``` 

From a `git blame` it seems like this issue was inadvertently introduced in #216 therefore has been the case since version 3.9.0.

**Comment by davidhassell** [comment]
Oops! Thanks for fixing it.
