### ISSUE TITLE
subtraction of cf.TimeDuration fails

### ISSUE THREAD

**Issue by dlrhodson** [NCAS-CMS/cf-python#287]
Hi Both!

Having a bit of trouble with cf.TimeDuration()  - looking at the code `def __sub__` appears to be missing[ this section](https://github.com/NCAS-CMS/cf-python/blob/master/cf/timeduration.py#L526) that appears in `def __add__` 
Is that why it fails? (I should test this!)

Cheers!
Dan

```
t=cf.Data(array=0.0,units='days since 2018-12-01')
t
<CF Data(): 2018-12-01 00:00:00>

 t+cf.TimeDuration(30,'day')
<CF Data(): 2018-12-31 00:00:00 gregorian>

 t-cf.TimeDuration(30,'day')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for -: 'Data' and 'TimeDuration'

```

  

```
>> cf.environment(paths=False)
Platform: Linux-3.10.0-1160.42.2.el7.x86_64-x86_64-with-glibc2.10
HDF5 library: 1.10.6
netcdf library: 4.7.4
udunits2 library: /apps/jasmin/jaspy/miniconda_envs/jaspy3.8/m3-4.9.2/envs/jaspy3.8-m3-4.9.2-r20211105/lib/libudunits2.so.0
Python: 3.8.12
netCDF4: 1.5.6
cftime: 1.5.1
numpy: 1.21.3
psutil: 5.8.0
scipy: 1.7.1
matplotlib: 3.4.3
ESMF: 8.1.0
cfdm: 1.9.0.1
cfunits: 3.3.4
cfplot: 3.1.16
cf: 3.11.0

```

**Comment by sadielbartholomew** [comment]
Hi Dan, thanks for raising this. Good spot, it does indeed look like a bug.

One of us will fix this shortly in the code, ready for the next release.

For now, do you have a workaround to allow you to do what you wanted to do despite the subtraction not working? If not, there are plenty of examples of operations on time durations by various approaches in our [cf.TimeDuration reference here](https://ncas-cms.github.io/cf-python/class/cf.TimeDuration.html?highlight=timeduration), is there something akin to an example there that could work instead?

**Comment by dlrhodson** [comment]
Hi Sadie!
   Yes - I had a look at the cf.TimeDuration examples - but there isn't a subtraction example :)
   I was wanted to subtract a month from a cf.Data containing a date, but the units changed with different data sources (e.g hours vs days) - hence cf.TimeDuration is idea here.
   In the end I worked out a workaround by checking the time axis units and subtracting the relevant float (24*30 vs 30) from the cf.Data. 
   It's probably a bit of an edge case use! But thought it worth mentioning :)
   
   Cheers!

**Comment by sadielbartholomew** [comment]
Thanks Dan, glad to hear you have a workaround for now. I'll push a fix in a moment to close this.

> It's probably a bit of an edge case use! But thought it worth mentioning :)

It is always helpful for folk to point out issues and potential issues, so thank you and please do keep sharing anything that seems amiss and/or any questions, etc.! And edge cases are possibly even more important for us to consider, as they are where bugs are generally more likely to appear. :slightly_smiling_face:
