### ISSUE TITLE
LAMA to Dask: address `TODODASK` items

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#433]
Whilst migrating the Data object itself from LAMA to Dask (notably migrating the methods in #295), we left various `TODODASK` markers. This is a bumper issue to record that these should be addressed for us to have considered #182 closable (addressing may in some cases mean converting to a standard `TODO` if that feels appropriate).

At the time of commenting, we have ~250 cases to resolve:

```console
$ pwd
/home/sadie/cf-python/cf
$ git grep "TODODASK" | wc -l
253
```

These have been classified as one of the following via a `TODODASK<optional marker>` searchable form (copied from https://github.com/NCAS-CMS/cf-python/pull/437#issue-1339605356):

* `TODODASKVER` for cases of placeholders for the final version for the release with the Dask migration which can now be sorted easily in a targeted way via a single sed or similar command;
* `TODODASKDOCS` for required docstring or documentation updates;
* `TODODASKMSG` for use-facing messages e.g. error messages;
* `TODODASKAPI` for API changes or considerations (potentially to bump to the release after Dask as per recent versioning discussions);
* `TODODASKDEPR` for anything deprecation related;
* anything else presently left as-is with `TODODASK` (miscellaneous etc.), these probably being the most meatly/difficult TODOs of all.

(Note that cases of one particular item can be found via something like (without the final pipe to `wc -l`):

```console
$ git grep "TODODASK" | grep -v "TODODASKVER" | grep -v "TODODASKDOCS" | grep -v "TODODASKMSG" | wc -l
45
```
)

Please add any notes and discussion points regarding these to this thread.

**Comment by davidhassell** [comment]
These items now dealt with, apart from the ones we want to leave there for later. Closing.
