### ISSUE TITLE
Document accepted argument types for `source` parameters

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#492]
For both the `Data` and `Field` classes, we should clarify types that are accepted and intended as valid inputs for the `source` constructor argument, as currently this is not specified leaving this ambiguous:

https://github.com/NCAS-CMS/cf-python/blob/d9d34beaa8a685e4e23c7e5009339e146b4cd22f/cf/data/data.py#L300-L304

https://github.com/NCAS-CMS/cf-python/blob/d9d34beaa8a685e4e23c7e5009339e146b4cd22f/cf/field.py#L337-L339

See the review comment https://github.com/NCAS-CMS/cf-python/pull/491#discussion_r1017602923 and the (short) ensuing thread for further context.

**Comment by davidhassell** [comment]
Just to add that there are no restrictions on the type of the `source` parameter, just that some objects may be more useful than others. For instance, one (the?) way to convert a dimension coordinate construct to an auxiliary coordinate construct  is
```python
In [28]: import cf; f = cf.example_field(0)

In [29]: d = f.dimension_coordinate('X')

In [30]: d
Out[30]: <CF DimensionCoordinate: longitude(8) degrees_east>

In [31]: a = cf.AuxiliaryCoordinate(source=d)

In [32]: a
Out[32]: <CF AuxiliaryCoordinate: longitude(8) degrees_east>

```

**Comment by davidhassell** [comment]
I propose addressing this first in `cfdm` since many of these docstrings are inherited from there. Once we've worked something out over there then the same framework can be applied to `cf`.

**Comment by davidhassell** [comment]
Fixed by https://github.com/NCAS-CMS/cfdm/pull/237
