### ISSUE TITLE
Set of related logos for the NCAS CF Python libraries

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#508]
We've noted previously that it would be good to get an official logo for each of the NCAS CF Python libraries. It would be good to get the ball rolling with thinking about designs and prototyping, so this issue can serve as a record of thoughts and progress.

By 'logo', I suggest we create, in line with most software logo resources, either an image and some text for the library name that is incorporated into the image, or separate to it but usually displayed by it.

I think given the links between these libraries, including the dependency for some pairs, it would be best (and also most efficient) to create a set of logos together that are inter-related in some aspect. to highlight the grouping, but also with slight differences across the set to distinguish.

Assuming agreement and ultimate permission from the original developers, I think the following five would be a good group to include as the set, but with an underlying idea for a theme to relate the logos, it should be quite simple to readily create a new design that fits with the rest should one or more new NCAS CF Python tools ermege (so we can keep in mind extensibility):
* cfdm;
* cf-python;
* cfunits;
* cf-plot;
* cf-checker.

If there is consensus for the above, then I believe we have to consider the following:
* what a good logo design would be (image, font, relative dimensions and placement, etc.);
* how we can vary the design so it has differences across the set of libraries (other than the library name text);
* what we should keep the same across the set to tie the logos together.

### General thoughts

My thoughts in brief are:

1. Given the CF Conventions are at the heart of the libraries it seems natural that this is highlighted in the logo. The 'CF' initials feature across the library names so it would be ideal to get those in the logo image rather than just the library name text.

2. Given the conventions are based on the Earth Sciences, having a sketch or plot of the all or part of the earth under some projection as the image seems sensible (at least, I can't think of other good ideas for what the image should be).

3. The earth is a bit difficult to draw out so it seems like a good idea to plot it for the image as a map projection using a tool, naturally cf-plot!

4. ...but a logo shouldn't be too detailed as it usually will be shown with small dimensions so any map projection plot used for the image should be quite simplistic as to not look too fussy or not work in fairly low-resolution.

5. A nice idea given the above would be to put the library name text over some earth map projection, but we might be straying too close to [the Cartopy logo](https://scitools.org.uk/cartopy/docs/latest/_static/cartopy.png) with that and it is best if we don't have a logo that resembles any of similar tools in use in our domain in case it looks like we copied or at least weren't very original...

### A proposal, with rough sketches

I thought about this earlier in the year and my favourite idea that I could come up with based on the above thoughts, which I will propose here as a candidate for the shared basis of the logos, is to decompose some elliptical-ish projection of the earth using some major displayed gridding lines into a 'C' and 'F' letter.

The following sketch tries to illustrate the idea, if you can forgive the crudeness (I used a crude paint tool app to draw on a plotted cartopy projection as it was the easiest to capture the idea):

![orig_white](https://user-images.githubusercontent.com/30274190/115313901-078aaa00-a16c-11eb-9e73-20d2e1ac4696.png)

Because the two letters might not be clear, I thought the other parts should be in a different colour, and made slightly smaller on the left and larger on the right so as to imply a forward trajectory, as if it were showing snapshots in time going forward in the plane, where lines as shown could help to emphasise that:

![final_logo_idea](https://user-images.githubusercontent.com/30274190/115314083-70722200-a16c-11eb-8110-1b3394040ea4.png)

My thinking is that the colours would be best coming from some simple [see (4)], probably blockfill, plot on the chosen projection, plotted using cf-plot. Then the grey divisions would be the same or a similar dataset also in blockfill but in a colour scale that is very different and more subtle, perhaps greyscale. They could be cut into placement as shown in the sketches manually using a photo editing tool.

#### Questions

It's not clear with the proposal as-is:

* where the library name text should go in each case;
* how to vary the design across the set;
* data and colour palettes, etc., to plot for each earth section,

**Comment by bewithankit** [comment]
Another input for the logo: Have the curve of the globe form a C and the axis of the globe a stylized f.

![IMG_20221205_094239](https://user-images.githubusercontent.com/83757805/205606682-37437df1-e36b-4d3b-b185-672b6d4eba7b.jpg)

**Comment by sadielbartholomew** [comment]
> Another input for the logo: Have the curve of the globe form a C and the axis of the globe a stylized f.

Love this one! I think it's far superior to my idea, by being elegant and simple. It's a +1 vote from me. :smiley:

**Comment by bewithankit** [comment]
Update: Showed it to David yesterday and he added that the equator could actually be used as the horizontal line for 𝑓.

![cfsuite_logo_v2](https://user-images.githubusercontent.com/83757805/206145857-fe9e217d-f7cf-4d0e-94ae-e98714dcf050.jpg)

**Comment by sadielbartholomew** [comment]
> the equator could actually be used as the horizontal line for 𝑓 and the C could be perceived as the atmosphere!

Oh that's incredible! I love how simple it is and yet so in-line with the context of cf-python :100: 

As far as I am concerned that's our logo right there! @bewithankit if you feel you have the time and would like to do so, it would be great to get a digital mock-up drawing of your drawing created.

I'm not sure if you have any experience with doing those, I don't have much, though I do believe from seeing a colleague create mock-ups previously that vector graphics software are the way to go to create final logo designs because SVG formats are 'transparent' against any background colour and scalable so can be used anywhere and at any (realistically-required) size on a site.

So if you have any experience or are happy to look into it and learn how to do it, trying to get a draft drawn up on a vector graphics software tool of your choice would be fantastic. I've heard great things about [Inkscape](https://inkscape.org/) which is free and open-source so should be simple to access and hopefully to use.

**Comment by sadielbartholomew** [comment]
I should add that I think your logo as above would be much better than the current CF Conventions logo too, so maybe once we have a final design for cf-python we can ask the governance team for the CF Conventions if they'd like to adopt the same, or a similar, logo (of course, only with your blessing and permission for the general case and specific designs since you are the designer!).

**Comment by davidhassell** [comment]
Lets keep it for ourselves - we don't want people conflating CF with cf-python ... :)

**Comment by sadielbartholomew** [comment]
> Lets keep it for ourselves - we don't want people conflating CF with cf-python

Fair enough! Would indeed be good to keep them distinguished by logo.
