### ISSUE TITLE
Issue with captions of some tutorials

### ISSUE THREAD

**Issue by bewithankit** [NCAS-CMS/cf-python#529]
The captions of the following tutorials either read **TODO** or **Create TODO**:

https://ncas-cms.github.io/cf-python/tutorial.html#subspaces-in-time
https://ncas-cms.github.io/cf-python/tutorial.html#subspace-mode
https://ncas-cms.github.io/cf-python/tutorial.html#multiple-dimensions
https://ncas-cms.github.io/cf-python/tutorial.html#assignment-by-metadata
https://ncas-cms.github.io/cf-python/tutorial.html#encapsulating-conditions
https://ncas-cms.github.io/cf-python/tutorial.html#compound-conditions

Should they be like that?

**Comment by davidhassell** [comment]
Thanks, Ankit, Indeed they shouldn't! Would you like to submit a pull request with some captions?

**Comment by sadielbartholomew** [comment]
I agree with David, it would be brilliant to get all of the TODOs left in the documentation filled out, if you get the chance Ankit. (And if it's not clear what some of the captions should read, just ask and we should be able to clarify.)

**Comment by bewithankit** [comment]
Yes, I would be happy TODO those!
