### ISSUE TITLE
Unable to calculate climatology:  "Can't collapse"

### ISSUE THREAD

**Issue by alvaroggc** [NCAS-CMS/cf-python#580]
Hello,

I'm trying to calculate daily climatology from monthly data.  My script looks something like this:

```
# standard packages
import datetime as dt

# 3rd party packages
import cf
import numpy as np


# load field (monthly data from 1850 to 2017)
sst, = cf.read(fsst).select_by_ncvar('SST_cpl')

# set bounds
sst.coord('T').set_bounds(sst.coord('T').create_bounds())
sst.coord('Y').set_bounds(sst.coord('Y').create_bounds())
sst.coord('X').set_bounds(sst.coord('X').create_bounds())

# change calendar
sst.coord('T').data.change_calendar('noleap', inplace=True)

# new temporal range
ti = cf.dt('1954-01-01 00:00:00', calendar='noleap')
tf = cf.dt('2016-12-31 00:00:00', calendar='noleap')

# retrieve time coordinate
time = sst.coord('T').copy()

# remove time coordinate bounds
time.del_bounds() if time.has_bounds() else None

# number of daily timesteps
nt = int((tf - ti) / dt.timedelta(days=1))

# daily time coordinate
time.set_data(np.array([ti + dt.timedelta(days=day) for day in range(nt+1)]))

# add new bounds
time.set_bounds(time.create_bounds())

# resample data
sst.regridc({'T': time}, axes=('T'), method='linear', inplace=True)

# calculate daily mean
sstc = sst.collapse('T: mean within years T: mean over years',
                    within_years=cf.D())
```

Resampling was successful with regridc function, but when i get to the collapse method, this error appears:

```
ValueError: Can't collapse: No contiguous groups within years spanning P1D (Y-M-D 00:00:00) were identified
```

I tried adding the `over_years` parameter so that i don't have boundary problems:
```
sstc = sst.collapse('T: mean within years T: mean over years',
                    within_years=cf.D(),
                    over_years=cf.year(cf.wi(1955, 2015)))
```
but that didn't solve the problem.

Is there something i'm missing?

**Comment by alvaroggc** [comment]
I forgot to add a few details:
- python: 3.9.13
- numpy: 1.23.1
- cf-python: 3.13.0

**Comment by sadielbartholomew** [comment]
Hi @alvaroggc, thanks so much for reporting this with your code included, and sorry that you were running into some difficulties in doing what you wanted to with cf-python. We've just done a major new release so we are a bit pre-occupied with that, but we can look into this soon. Out of interest, if you install the new version (3.14.0) do you see the same outputs or does anything change?

**Comment by davidhassell** [comment]
Hi @alvaroggc, thanks for the question. Did you mean to collapse the returned result of the `regridc` command rather than `sst`, the un-regridded field?

Thanks,
David

**Comment by alvaroggc** [comment]
Hi @davidhassell that's exactly what i'm trying to do, so that at the end I have two fields, the historical data (sst) and the climatology (sstc).

@sadielbartholomew i've tried installing 3.14.0 but I'm having problems with the dependencies (now my virtual environment doesn't find my esmf package as I updated cf-python through pip rather than conda). I'll wait until de 3.14.0 version gets to the conda repository to test this new version.

BTW, during this time I try version 3.13.1 and got the same results mention before.

**Comment by davidhassell** [comment]
Oh, sorry, my mistake! I missed the `inplace=True` part.

It would very useful to check  at the time coordinates and bounds of `sst`, something like
```python
t = sst.coord('T')
print(t.datetime_array)
print(t.bounds.datetime_array)
```
That might be a lot to post, but the first few values might tell us enough ...

**Comment by alvaroggc** [comment]
I just checked the values of the time coordinate and (for me) everything seems ok :(

```
In [n]: t = sst.coord('T')
In [n+1]: t.datetime_array[[0, 1, 2, -3, -2, -1]]
Out[n+1]: 
array([cftime.DatetimeNoLeap(1954, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1954, 1, 2, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1954, 1, 3, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2016, 12, 29, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2016, 12, 30, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2016, 12, 31, 0, 0, 0, 0, has_year_zero=True)],
      dtype=object)

In [n+2]: t.bounds.datetime_array[[0, 1, 2, -3, -2, -1]]
Out[n+2]:
array([[cftime.DatetimeNoLeap(1953, 12, 31, 12, 0, 0, 0, has_year_zero=True),
        cftime.DatetimeNoLeap(1954, 1, 1, 12, 0, 0, 0, has_year_zero=True)],
       [cftime.DatetimeNoLeap(1954, 1, 1, 12, 0, 0, 0, has_year_zero=True),
        cftime.DatetimeNoLeap(1954, 1, 2, 12, 0, 0, 0, has_year_zero=True)],
       [cftime.DatetimeNoLeap(1954, 1, 2, 12, 0, 0, 0, has_year_zero=True),
        cftime.DatetimeNoLeap(1954, 1, 3, 12, 0, 0, 0, has_year_zero=True)],
       [cftime.DatetimeNoLeap(2016, 12, 28, 12, 0, 0, 0, has_year_zero=True),
        cftime.DatetimeNoLeap(2016, 12, 29, 12, 0, 0, 0, has_year_zero=True)],
       [cftime.DatetimeNoLeap(2016, 12, 29, 12, 0, 0, 0, has_year_zero=True),
        cftime.DatetimeNoLeap(2016, 12, 30, 12, 0, 0, 0, has_year_zero=True)],
       [cftime.DatetimeNoLeap(2016, 12, 30, 12, 0, 0, 0, has_year_zero=True),
        cftime.DatetimeNoLeap(2016, 12, 31, 12, 0, 0, 0, has_year_zero=True)]],
      dtype=object)
```

This time I use different versions of the following packages:
- `cf-python: 3.13.1`
- `esmf: 8.3.1` (version `8.4.0` wasn't being recognized in my conda environment anymore)

**Comment by davidhassell** [comment]
Hi @alvaroggc,

Thanks for the results. I wonder if asking for `within_years=cf.D()` when the data do not have sub-daily resolution is triggering the error - I'll investigate further.

**Comment by davidhassell** [comment]
Hi @alvaroggc,

Well, it works in my test example if you shift the time coordinates by 0.5 days, i.e. so that the bounds are at 0Z and the cell coordinate is at 12Z.

Does that solve the problem?

It _should_ work with what you were originally doing, though, and you may well require the bounds at 12Z, so I shall find and fix this bug.

**Comment by davidhassell** [comment]
Hi @alvaroggc,

OK not a bug afterall, I think.  `TimeInterval` objects, of which `cf.D(...)` is one, always have an offset at which they are anchored, and for days that offset defaults to `0Z`. SO in your original code it was looking for days that start and finish at 0Z and wasn't finding any, since your days start and finish at 12Z. 

Try this:
```python
# calculate daily mean
sstc = sst.collapse('T: mean within years T: mean over years',
                    within_years=cf.D(hour=12))
```
which is saying that "I'm defining my days to start at 12Z, not 0Z".

**Comment by alvaroggc** [comment]
Hi @davidhassell 

Now it works! I would have never find that detail by myself.

Thank you so much and all the team for the amazing work :)

Closing this issue.

**Comment by davidhassell** [comment]
Thnaks @alvaroggc  - "_I would have never find that detail by myself_" is a good point. We'll add a [recipe](https://ncas-cms.github.io/cf-python/recipes.html) that demonstrates this.
