### ISSUE TITLE
Documentation: printable cheat sheet including selected recipes

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#591]
Some libraries provide 'cheat sheets' i.e. summary reference pages, designed to be online or on-paper or both, summarising important parts of their library's API and/or functionality and/or outputs. They may be listed under other names than 'cheat sheet', but the principle is the same, e.g. ''10 Minutes to X' (or 'N minutes to X') pages are quite similar in scope.

It would be nice if we can have one of more cheat sheets for cf-python. They could include summaries of our core functionalities, some notable recipes, and , etc.

Ideally this would be available in a printable format, suitable for A3 or A4 size printing, so anyone old school or otherwise can print one out to refer to off-screen. It could be divided into beginner, intermediate and advanced sections or sheets also.

Nice examples I have seen recently as inspiration are:

* [matplotlib](https://matplotlib.org/cheatsheets/);
* [pandas](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf), linked from [this page](https://pandas.pydata.org/docs/getting_started/index.html?highlight=cheat#tutorials);
* [dask](https://docs.dask.org/en/stable/10-minutes-to-dask.html).

***

This is something else you might want to work on at some point, @bewithankit!

**Comment by bewithankit** [comment]
Wow! It'll be so cool to have one of these Cheat Sheets for `cf-python`! Thank you for the idea Sadie!

**Comment by davidhassell** [comment]
Discussed this week off-line with @bewithankit ...
