### ISSUE TITLE
Regridding error with cf python saying that ESMF library not loaded

### ISSUE THREAD

**Issue by lkgohar** [NCAS-CMS/cf-python#595]
Hello,
I am sure this is a very basic question but I am struggling with getting the cf python regrids to work. The error tells me that the ESMF libraries are not loaded and indeed when typing cf.environment(paths=False) I am told that ESMF: not available.  I use a conda environment for installing cf -python which includes installing esmpy. When my cf python environment is activate and list the packages installed the list includes:
esmf                      8.4.0           mpi_mpich_hc592774_104    conda-forge
esmpy                     8.4.0           mpi_mpich_py311hf216de5_102    conda-forge
So I am at a loss to why cf-python is unable to access the ESMF libraries. I am hoping you can help.

**Comment by davidhassell** [comment]
Hi Laila,

Sorry about this. ESMF changed their API and cf-python can't cope yet, so we have to pin the version to 8.2.0. This wasn't in the docs, but I have added it just now! (https://ncas-cms.github.io/cf-python/installation.html#optional).

Thanks for letting us know about the problem.
David

**Comment by lkgohar** [comment]
Hi David,
Yes - working fine now thank you.
All the best,
Laila


Dr Laila K. Gohar
***@***.***
Department of Meteorology,
University of Reading,
Brian Hoskins Building,
Earley Gate, Whiteknights Road,
Reading, UK
RG6 6ET
Tel:     +44(0)330 135 1468
Fax:    +44(0)118 378 5615
E-mail:  ***@***.******@***.***> Website: www.metoffice.gov.uk<http://www.metoffice.gov.uk/>

***@***.***
