### ISSUE TITLE
Consolidate & tidy imports in import-heavy modules

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#63]
Understandably it is not high on the developer priority list, but from working with certain modules with lots of ``import`` statements, I've noticed certain items aren't grouped together &/or are in places I would not expect them to be relative to other imports.

Looking at ``data.data`` & ``field`` which are particularly import-heavy, it seems that generally (though there are outliers to change to follow suit) the intended order is, with alphabetical ordering as appropriate inside each:

1. General Python in-built modules [though some at position 4 for ``data.data``];
2. SciPy & NumPy;
3. Other CF modules e.g. ``cfdm``;
4. Relative ``cf-python`` imports (all ``..<name>`` then all ``.<name>``);
5. ``mpi4py``-related.

I'm happy to do a small tidy on those modules. More generally, though, this Issue could act as a document describing the desired organisational rules so that we are aware where to put any ``import`` statements we are adding to keep them in a known order as we go.

@davidhassell before I rearrange some out-of-place imports, can I check with you that the above ordering is the one intended & still intended? I also have a few questions. Some items are listed out separately for no obvious reason. Can & should the following sets be combined (via e.g. ``from .data import (...)``) or are they  intentionally like so?:

https://github.com/NCAS-CMS/cf-python/blob/defa44fff6d146da1703bf4133af56afff19a14f/cf/field.py#L73-L77

and:

https://github.com/NCAS-CMS/cf-python/blob/defa44fff6d146da1703bf4133af56afff19a14f/cf/field.py#L45-L57

With something like this, it does seem appropriate to use multiple groups, but instead ones organised by some categories e.g. one for the ``as`` statement, one private methods & one for the rest (all internally alphabetical)?:

https://github.com/NCAS-CMS/cf-python/blob/defa44fff6d146da1703bf4133af56afff19a14f/cf/data/data.py#L104-L114

 Structurally, for modules with sizable lists of imports from a given module, notably ``numpy``(``.ma``), e.g in the ``data.data`` module:

https://github.com/NCAS-CMS/cf-python/blob/defa44fff6d146da1703bf4133af56afff19a14f/cf/data/data.py#L10-L84

would you be opposed to me changing it to the following, which is valid ``import`` syntax & which avoids the duplication of the import statement & makes it a bit easier to check the methods?:

```python
from numpy import (
    arange            as numpy_arange,
    arccos            as numpy_arccos,
    arccosh           as numpy_arccosh,
    arcsin            as numpy_arcsin,
    arcsinh           as numpy_arcsinh,
    ...
)
from numpy.ma import (
    ...
)
```

**Comment by sadielbartholomew** [comment]
I've recently heard about an auto-formatting tool that we can use to organise imports systematically, towards resolving this minor Issue, without any work (since it is quite frivolous and we wouldn't ever spend time dong it manually): [`isort`](https://github.com/PyCQA/isort).

When there's a quiet moment I can add apply it across the codebase and add it to run in the pre-commit hooks (and therefore also on the linting Actions workflow), if there is agreement.

**Comment by davidhassell** [comment]
Agreed.
