### ISSUE TITLE
Adapt to ESMF Python interface module name change

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#633]
At ESMF release 8.4.0 the Python module changed canonical name, as covered in [the relevant Changelog entry](https://github.com/esmf-org/esmf/releases/tag/v8.4.0):

> The Python module name for ESMPy was changed in this release from “ESMF” to “esmpy” for better alignment with [Python Enhancement Proposal (PEP)](https://peps.python.org/) guidelines. This change will require user code changes! ESMPy users will have to do a global search and replace on their scripts to adjust to the module name change. Also notice that the internal ESMF source tree directory structure has changed, moving ./src/addon/ESMPy to ./src/addon/esmpy. This might affect anybody keeping an ESMF repository clone, and maintaining scripts that depend on the internal directory naming.

We therefore need to update all references to the module accordingly. Addressing that should fix the sub-issue of #629.

Currently, the ESMF Python interface is not being picked up within `cf`, for the above reason, e.g. when `conda list` confirms I have `esmf` installed (version `8.4.1` in this case) I see:

```ipython
>>> import cf
>>> cf.environment()
Platform: Linux-4.15.0-54-generic-x86_64-with-glibc2.10 
HDF5 library: 1.14.0 
netcdf library: 4.9.2 
udunits2 library: /home/sadie/anaconda3/envs/cf-env/lib/libudunits2.so.0 
ESMF: not available
...
```

Thanks to @ajheaps for the heads up about this!

**Comment by davidhassell** [comment]
Thanks for putting this up, Sadie.

Do we want/need to support versions before and after the change?

**Comment by sadielbartholomew** [comment]
> Do we want/need to support versions before and after the change?

Ooh, good question! I'd say we probably should support both for a little while, perhaps until our `cf` version `4.0.0`? But from a `git grep "ESMF" | wc -l` in the `<cf repo>/cf/` directory there are presently ~190 references (obviously some being comments and documentation but not all) so it might be a bit ugly to handle. (I don't personally mind the trouble though, as the previous module name did annoy me with it being so unstandardised in its capitalisation :smile: .)

**Comment by davidhassell** [comment]
It'd be good to get this in for 3.15.0
