### ISSUE TITLE
Docs: immobile navigation menu can be cut off

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#658]
Equivalent to NCAS-CMS/cfdm#50, but more urgent for cf-python due to that menu being significantly longer than the cfdm docs one as of late, due to various new sections being added over the last few years.

As a solution, I have a strong preference for us just adding a scrollbar to the sidebar. Any disagreement on that then please do shout! But the scrollbar seems like a natural solution that is (probably) easy enough to add.

**Comment by sadielbartholomew** [comment]
Hi @bewithankit, I realised the Issue I raised about this was on cfdm rather than cf, so I've created an equivalent. If you can solve this for one library, we might as well add it to all three (cfunits being the third). Thanks!

**Comment by bewithankit** [comment]
One more thought of nesting some of the sections of the sidebar: Tutorial and Analysis, Releases and Change log, Introduction and Performance? I wondered if Analysis is a copy of the Tutorial why are they separate?
