### ISSUE TITLE
Protect your `main` branch

### ISSUE THREAD

**Issue by valeriupredoi** [NCAS-CMS/cf-python#685]
Hey folks, noticed your `main` branch is not protected (from force pushes etc) - you should do that, I can do it too but I don't think it'd be nice if I did that :grin: :beer:

**Comment by sadielbartholomew** [comment]
Thanks V but we do occasionally, though obviously very carefully, use force pushes (for good reason!) so I don't think this would be useful for us for the `cf-python` repo, so I am closing this. (We've ignored the GitHub warning about protecting the default branch for long enough anyway :smile: .)
