### ISSUE TITLE
Record cell characteristics from aggregation cell conditions

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cf-python#692]
Since 3.15.2, the `cells` keyword of `cf.aggregate` allows fields to be aggregated sperately according to the characteristics of their dimension coordinates - namely cell spacing and  cell size.

It would be useful to automatically record these characteristics on the aggregated fields, so that it is easy to see afterwards which conditions were passed.

Since the characteristics apply to dimension coordinate constructs only, they should be recorded on those constructs.

I propose four new `DimensionCoordinate` methods of `[del|get|has|set]_cell_characterstics` to allow the cell characteristics to be stored and subsequently accessed.

**Comment by bnlawrence** [comment]
Would we have a controlled vocabulary of possible characteristics?

**Comment by davidhassell** [comment]
> Would we have a controlled vocabulary of possible characteristics?

No - that would be up to a user application (such as cfstore) to map from a saved numerical-like characteristic of (say) `{'cellsize': <CF Query: (wi [28, 31] day)>}` to something that that application likes.

other examples of stored characteristics that apply to CANARI

```python
  {'cellsize': <CF Query: (isclose 1 hour)>}

  {'cellsize': <CF Query: (isclose 0 hour)>,
   'spacing': <CF Query: (isclose 1 hour)>}

  {'cellsize': <CF Query: (isclose 3 hour)>}

  {'cellsize': <CF Query: (isclose 0 hour)>,
   'spacing': <CF Query: (isclose 3 hour)>}

  {'cellsize': <CF Query: (isclose 6 hour)>}

  {'cellsize': <CF Query: (isclose 0 hour)>,
   'spacing': <CF Query: (isclose 6 hour)>}

  {'cellsize': <CF Query: (isclose 1 day)>}
```

E.g. 
```python
if cf.wi(28, 31, 'd').equals(cellsize):
    cellsize = "1 month"
```
```python
if cf.isclose(0, 'h').equals(cellsize) and cf.isclose(3, 'h').equals(spacing):
    cellsize = "0 hour"
    spacing = "3 hour"
```

It's possible to be more general if you know all characteristics are `cf.Query` objects (which you will know):
```python
if char.operator in ('isclose', 'eq'):
    x = char.value
    char = f"{x.datum()} {x.Units.formatted(names=True)}"
elif cf.wi(28, 31, 'd').equals(char):
    char = "1 month"
elif cf.wi(360, 366, 'd').equals(char):
    char = "1 year"
```
