### ISSUE TITLE
Allow 3-d spherical regridding, including an option to regrid the vertical axis in logarithmic coordinates

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cf-python#715]
Currently spherical regridding is only 2-d, but it can be done in 3-d. Treatment of the vertical axis is crucial, so an option to calculate the regrid weights based on the natural logarithm of the vertical coordinates would be useful. It must be possible to provide vertical either 1-d or 3-d  vertical coordinates.

The option to identify an vertical axis in Cartesian regridding, and to specify logarithmic vertical coordinates, would also be good.

**Comment by brogalla** [comment]
Thanks for adding this functionality, I appreciate it! Do you plan to add 3D conservative regridding (like in esmpy) as well?
