### ISSUE TITLE
documentation error in https://ncas-cms.github.io/cf-python/method/cf.Field.coordinates.html

### ISSUE THREAD

**Issue by JonathanGregory** [NCAS-CMS/cf-python#748]
Something has been garbled here, I think:

**Examples**
```
>> f.coordinates() Constructs: }

>> f.coordinates() Constructs: ‘auxiliarycoordinate0’: <CF AuxiliaryCoordinate: latitude(10, 9) degrees_N>, ‘auxiliarycoordinate1’: <CF AuxiliaryCoordinate: longitude(9, 10) degrees_E>,
```
etc. When I try this method, I get

```
>>> f.coordinates()
<CF Constructs: dimension_coordinate(3)>
```

**Comment by davidhassell** [comment]
Thanks, Jonathan. Could you please post the URL of the offending page? I can't find it by grepping in the code nor the html!

**Comment by JonathanGregory** [comment]
It's in the title of the issue viz. https://ncas-cms.github.io/cf-python/method/cf.Field.coordinates.html

**Comment by JonathanGregory** [comment]
Thanks for fixing it.
