### ISSUE TITLE
CFAPyX Support - Complete groups in CFA

### ISSUE THREAD

**Issue by dwest77a** [NCAS-CMS/cf-python#798]
The Xarray-implemented CFA-netCDF reader has an issue with groups because Xarray does not support the typical group hierarchy of netCDF4. Xarray is capable of opening netCDF4 groups as separate Datasets but this requires the group to be 'complete' i.e self-describing in terms of dimension/coordinate variables. A set of groups which share a global dimension would therefore not be allowed with the current implementation.

Possible solutions to this issue are:
 1. Ensuring CFA-netCDF groups are complete i.e aggregation groups contain all the data and metadata required to serve a specific variable (time/lat/lon would all be part of the group)

 2. Adjusting the CFAPyX (Xarray-CFA implementation) package to expand groups out into their respective variables, then using either a variable attribute or other form to represent where the variable `originated from` in the source data.

**Comment by davidhassell** [comment]
Er, is this a cf-python issue :)

**Comment by davidhassell** [comment]
I think we can close this ... Dan and I have talked offline and agreed that it's not a cf-python (nor CF) issue (right?).
